name: LogTransaction
version: '${project.version}'
main: fr.lefoutrolleur.logtransaction.LogTransaction
api-version: '1.20'
database: true

depend:
  - CMI
  - CoinsEngines
load: STARTUP
commands:
  retrievetransaction:
    name : Retrieve Transaction
    aliases:
      - rt
