name: LogTransaction
version: '${project.version}'
main: fr.lefoutrolleur.logtransaction.LogTransaction
api-version: '1.20'
load: STARTUP
commands:
  savetransaction:
    name: Log Transaction
    description: Log Transaction(Plugin Only)
    aliases:
      - st
  retrievetransaction:
    name : Retrieve Transaction
    aliases:
      - rt
