name: LogTransaction
version: '${project.version}'
main: fr.lefoutrolleur.logtransaction.LogTransaction
api-version: '1.20'
load: STARTUP
commands:
  logtransaction:
    name: Log Transaction
    description: Log Transaction(Plugin Only)
  retrievetransaction:
    name : Retrieve Transaction
