name: LogTransaction
version: '1.0-RELEASE'
main: fr.lefoutrolleur.logtransaction.LogTransaction
api-version: '1.20'
database: true

depend:
  - nightcore
  - CoinsEngine
  - CMI
load: STARTUP
commands:
  retrievetransaction: