name: LogTransaction
version: '${project.version}'
main: fr.lefoutrolleur.logtransaction.LogTransaction
api-version: '1.20'
database: true

depend:
  - CMI
  - nightcore
  - CoinsEngine
load: STARTUP
commands:
  retrievetransaction:
    name : Retrieve Transactions of a player in a currency
    aliases:
      - rt
